### ISSUE TITLE
Unwind with data from layout2

### ISSUE THREAD

**Issue by Angela-Mari** [Angela-Mari/Mood-Board-Designer#1]

**Comment by eml2017** [comment]
Found on branch `imagePicker`

Note: Layout1 and Layout2 condensed into one file (`AddBoardViewController.swift`), so it'll match the stuff for layout1

**Comment by eml2017** [comment]
> Found on branch `imagePicker`
> 
> Note: Layout1 and Layout2 condensed into one file (`AddBoardViewController.swift`), so it'll match the stuff for layout1
