### ISSUE TITLE
have youtube video for sound

### ISSUE THREAD

**Issue by Angela-Mari** [Angela-Mari/Mood-Board-Designer#5]

**Comment by eml2017** [comment]
On branch `youtube`

Note: I seem to be having some trouble with the Cocoapods. Everything works as planned on seperate project. Any error-generating code is commented out with a note (see `Layout1ViewController.swift` and `Layout2ViewController.swift`).

**Comment by eml2017** [comment]
> On branch `youtube`
> 
> Note: I seem to be having some trouble with the Cocoapods. Everything works as planned on seperate project. Any error-generating code is commented out with a note (see `Layout1ViewController.swift` and `Layout2ViewController.swift`).

Oof yeah I think I installed the Cocoapod incorrectly (after rewatching 11/18 lecture for PA8).

**Comment by eml2017** [comment]
**Update:** `youtube` branch should be all good to go (turns out I forgot to uncomment the platform # in the Podfile)! I'll add this YouTube functionality to the `imagePicker` branch so all the "add" stuff is on one branch.
